# Use an official Node.js image
FROM node:22-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json ./
COPY package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the app's files
#COPY . ./

# Expose the port your Express app runs on
EXPOSE 3001

# Start the app
CMD ["npm", "run", "dev"]
